spring:
  application:
    name: kafka-app
  kafka:
    bootstrap-servers: localhost:19092
    producer:
      topic: kafka_demo
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: kafka-app
      topic: kafka_demo
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    security:
      protocol: PLAINTEXT